from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.env["CXX"]:
        return False
    if not conf.check_cfg(package="adplug", atleast_version="2.2", uselib_store="adplug", args="--cflags --libs"):
        return False
    return True

configure, build = plugin("adplug", configure=plugin_configure,
    source=["adplug.cpp"], libs=["adplug"], tool="cxx")
